config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # root 'home#index'
  root 'friends#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all.sort_by { |friend| friend.created_at }.reverse
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authenticated To Edit This Ticket" if @friend.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is Haojin Li."
    @answer = 2 + 2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <label class="label">First Name</label>
      <div class="control has-icons-left">
        <%= form.text_field :first_name, class:"input"%>
        <span class="icon is-small is-left">
          <i class="fa-solid fa-user"></i>
        </span>
      </div>
  </div>

  <div class="field">
    <label class="label">Last Name</label>
      <div class="control has-icons-left">
        <%= form.text_field :last_name, class:"input"%>
        <span class="icon is-small is-left">
          <i class="fa-solid fa-user"></i>
        </span>
      </div>
  </div>

  <div class="field">
    <label class="label">Email</label>
      <div class="control has-icons-left">
        <%= form.text_field :email, class:"input"%>
        <span class="icon is-small is-left">
          <i class="fa-solid fa-envelope"></i>
        </span>
      </div>
  </div>

  <div class="field">
    <label class="label">Phone</label>
      <div class="control has-icons-left">
      <%= form.text_field :phone, class:"input"%>
        <span class="icon is-small is-left">
          <i class="fa-solid fa-phone"></i>
        </span>

      </div>
  </div>

  <div class="field">
    <label class="label">Issue Description</label>
      <div class="control has-icons-left">
        <%= form.text_field :twitter, class:"input"%>
        <span class="icon is-small is-left">
          <i class="fa-solid fa-message"></i>
        </span>
      </div>
  </div>

  <br/>

  <div class="field">
      <%= form.number_field :user_id, id: :friend_user_id, class:"input", value:current_user.id, type:"hidden" %>
  </div>

  <div class="field">
    <div class="control">
      <%= form.submit class:"button is-success", value: "Create ticket" %>
    </div>

  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Issue:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">Editing Ticket</div>

<br/>

<%= render "form", friend: @friend %>


</div>
</div>

<br>
<div>
  <div class="field is-grouped">
    <p class="control">
      <%= link_to "Show this ticket", @friend, class:"button is-info" %>
    </p>
    <p class="control">
      <%= link_to "Back", friends_path, class:"button" %>
    </p>
  </div>
</div>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<div class="container is-fluid">
<div class="card">

  <div class="card-content">
  <div class="title">Tickets</div>
  <br />
  <div class="table-container">
<table class="table is-striped is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Issue Description</th>
      <th>Created Date</th>
      <th>Update Date</th>
    </tr>
  </thead>

  <tbody>

    <% @friends.each do |friend| %>
      <% if friend.user == current_user%>
      <tr>

        <td><%= link_to friend.first_name + " "+friend.last_name, friend%></td>
        <td><%= friend.email%></td>
        <td><%= friend.phone%></td>
        <td><%= friend.twitter%></td>
        <td><%= friend.created_at.strftime('%m-%d-%Y')%></td>
        <td><%= friend.updated_at.strftime('%m-%d-%Y')%></td>
      </tr>
      <% end %>
    <% end %>

  </tbody>

</table>

<%= link_to "New ticket", new_friend_path, class:"button is-success" %>

</div>
</div>
</div>
</div>

<% else %>

<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      Welcome to Duke FixIt!
    </p>
    <br/>
    <p class="subtitle">
      FixIt issue tracking system for problems that students notice around campus, such as a cracked dorm window, malfunctioning handicap door button, etc.
    </p>
  </div>
</section>


<% end %>

app/views/friends/new.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">Add Ticket</div>

<br/>
<%= render "form", friend: @friend %>

<div>

</div>
</div>

</div>
<br/>
<%= link_to "Back to lists", friends_path, class:"button is-link" %>

</div>

app/views/friends/show.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">

    <div class="title">
      <i class="fas fa-user"></i>
      &nbsp
      <%= @friend.first_name%>
      <%= @friend.last_name%>
    </div>
    <div class="content">
    <i class="fas fa-envelope"></i>
      <strong>Email:</strong>
      <%= @friend.email%>
      <br/>
      <i class="fas fa-phone"></i>
      <strong>Phone:</strong>
      <%= @friend.phone%>
      <br/>
      <br/>

      <div class="notification is-primary is-light">
      <h2>Issue:</h2>
        <%= @friend.twitter%>
      </div>
      <i class="fas fa-calendar-alt"></i>
      <strong>Created at:</strong>
      <%= @friend.created_at.strftime('%H:%M:%S, %m-%d-%Y')%>
      &nbsp &nbsp
      <i class="fas fa-calendar-check"></i>
      <strong>Updated at:</strong>
      <%= @friend.updated_at.strftime('%H:%M:%S, %m-%d-%Y')%>
      <br/>

      </div>
    </div>
  </div>
<br/>
<div class="field is-grouped">
  <p class="control">
    <%= link_to "Edit", edit_friend_path(@friend), class:"button is-link"%>
  </p>
  <p class="control">
    <%= link_to "Back", friends_path, class:"button" %>
  </p>
  <% if user_signed_in? %>
  <p class="control">
    <%= button_to "Delete", @friend, method: :delete, class:"button is-danger" %>
  </p>
  <% end %>
</div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="container is-fluid">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="https://cdn.jsdelivr.net/gh/declan-haojin/blog-image//duke/FixIt-logo.png" width="130" height="30">
    </a>
    <%# <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="false"></span>
      <span aria-hidden="false"></span>
      <span aria-hidden="false"></span>
    </a> %>
  </div>

  <div id="navMenu" class="navbar-menu is-active">
    <div class="navbar-start">
        <%= link_to 'Home', root_path, class:"navbar-item" %>
        <%= link_to 'New Ticket', new_friend_path, class:"navbar-item"%>
        <%= link_to 'About Us', home_about_path, class:"navbar-item"%>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

            <% if user_signed_in? %>
            <%= link_to 'Profile', edit_user_registration_path, class:"button is-primary"%>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"button is-light"%>
            <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class:"button is-primary"%>
              <%= link_to 'Log in', new_user_session_path, class:"button is-light"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>
<div>
</nav>

app/views/home/about.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">About Us</div>
<br/>

<p>FixIt issue tracking system for problems that students notice around campus, such as a cracked dorm window, malfunctioning handicap door button, etc.</p>
</div>
</div>
</div>

app/views/home/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      Welcome to Duke FixIt!
    </p>
    <br/>
    <p class="subtitle">
      FixIt issue tracking system for problems that students notice around campus, such as a cracked dorm window, malfunctioning handicap door button, etc.
    </p>
  </div>
</section>

app/views/layouts/_notification.html.erb
<div class="notification is-warning">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Duke FixIt</title>
    <link rel="icon" type="image/x-icon" href="https://cdn.jsdelivr.net/gh/declan-haojin/blog-image//duke/FixIt favicon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/0785af7e62.js" crossorigin="anonymous"></script>
  </head>
  <body>

    <%= render 'home/header' %>

    <br/>
    <div class="container">
      <% if notice %>
       <%= render "layouts/notification"%>
      <% end %>

    <%= yield %>

    </div>
  </body>

   </br>
  <footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Duke FixIt</strong> by <a href="https://haojin.li">Haojin Li</a>. The source code is licensed under the
      <a href="http://opensource.org/licenses/mit-license.php">MIT License</a>.
    </p>
  </div>
</footer>
</html>